version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/pern-todo

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pern-todo
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
